NUM_GPUS: 1
DATASET:
  CROP_SIZE: 513
  SCALE_FROM: 0.5
  SCALE_TO: 2.0
  ROOT: "../1sw/data"
  NAME: 'sbd'
  FILENAME: "train_augvoc"
TRAIN:
  BATCH_SIZE: 8
  NUM_EPOCHS: 50
  NUM_WORKERS: 8
  PRETRAIN: 5
TEST:
  METHOD: "multiscale"
  DATA_ROOT: "../1sw/data"
  FLIP: False
  BATCH_SIZE: 1 # 4 scales, +1 flip for each
  PAD_SIZE: [1024, 1024]
  SCALES: [1] #[1, 0.5, 1.5, 2.0]
  FP_CUT_SCORE: 0.1
  BG_POW: 3
  USE_GT_LABELS: False
