NUM_GPUS: 1
DATASET:
  CROP_SIZE: 384 #321
  SCALE_FROM: 0.9
  SCALE_TO: 1.0
  ROOT: "../1sw/data"
  NAME: 'sbd'
  FILENAME: "train_augvoc"
TRAIN:
  BATCH_SIZE: 8
  NUM_EPOCHS: 25
  NUM_WORKERS: 8
  PRETRAIN: 5
NET:
  BACKBONE: "resnet38"
  MODEL: "CAM_CASA_WGAP_tf_v9_2"
  PRE_WEIGHTS_PATH: "../1sw/weights/ilsvrc-cls_rna-a1_cls1000_ep-0001.pth"
  LR: 0.001
  OPT: "SGD"
  LOSS: "SoftMargin"
  WEIGHT_DECAY: 0.0005
  PAMR_ITER: 10
  FOCAL_LAMBDA: 0.01
  FOCAL_P: 3
  SG_PSI: 0.3
TEST:
  METHOD: "multiscale"
  DATA_ROOT: "../1sw/data"
  FLIP: False
  BATCH_SIZE: 1 # 4 scales, +1 flip for each
  PAD_SIZE: [0, 0] #[1024, 1024]
  SCALES: [1] #[1, 0.5, 1.5, 2.0]
  FP_CUT_SCORE: 0.1
  BG_POW: 3  #1 or 3
  USE_GT_LABELS: True
